name: Check Markdown links

on: 
  push:
  pull_request:
  schedule:
  - cron: "0 9 * * *" # Runs at 09:00 UTC every day

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@master
      with:
        use-quiet-mode: 'no'
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/.mlc_config.json'
